name: Deploy to firebase

on:
  release:
    types:
      - published
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  integration:
    runs-on: ubuntu-22.04
    container: node:18-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: |
          yarn install --network-timeout 1000000000
      # - name: Unit Tests
      #   run: |
      #     yarn test-coverage
      - name: Build
        run: |
          yarn build

  deploy:
    needs: integration
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Firebase
      uses: mohammed-atif/firebase-publish-react@v1.0
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
