name: Deploy to firebase

on:
  release:
    types:
      - published
  push:
    branches:
      - "main"

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Setup the code
      run: yarn install --production --network-timeout 1000000000
    # - name: Test the code
      # run: npm test
    - name: Deploy to Firebase
      uses: mohammed-atif/firebase-publish-react@v1.0
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
