name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    container: node:18-alpine
    env:
      PUBLIC_FIREBASE_API_KEY: ${{secrets.PUBLIC_FIREBASE_API_KEY}}
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          yarn install --network-timeout 1000000000
      - name: Build
        run: |
          yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: tinithai-3b0eb
