name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_deploy:
    permissions: write-all
    runs-on: ubuntu-22.04
    container: node:18-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_PUBLIC_FIREBASE_API_KEY: ${{ secrets.PUBLIC_FIREBASE_API_KEY }}
          file_name: .env
          fail_on_empty: true
      - name: Confirm env file
        run: cat .env
      - name: Install
        run: |
          yarn install --frozen-lockfile --network-timeout 1000000000
      - name: Build
        env:
          PUBLIC_FIREBASE_API_KEY: ${{ secrets.PUBLIC_FIREBASE_API_KEY }}
        run: |
          yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: tinithai-3b0eb
